insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (1, 'Germany', 'Düsseldorf', '40215', '87693 Raven Place');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (2, 'France', 'Goussainville', '95697 CEDEX', '1644 Hallows Lane');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (3, 'France', 'Pau', '64029 CEDEX 9', '71 Anhalt Plaza');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (4, 'France', 'Villefranche-sur-Mer', '06239 CEDEX', '133 Clarendon Hill');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (5, 'France', 'Lyon', '69367 CEDEX 07', '4931 Waubesa Circle');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (6, 'France', 'Blois', '41015 CEDEX', '9778 Wayridge Hill');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (7, 'France', 'Choisy-le-Roi', '94604 CEDEX', '3198 Gerald Center');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (8, 'Germany', 'München', '81373', '896 Rigney Alley');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (9, 'France', 'Bobigny', '93017 CEDEX', '40 Hoffman Plaza');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (10, 'France', 'Massy', '91309 CEDEX', '5 Lien Road');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (11, 'France', 'Castres', '81109 CEDEX', '0351 Kinsman Court');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (12, 'France', 'Marseille', '13281 CEDEX 06', '59938 Menomonie Park');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (13, 'France', 'Tarbes', '65022 CEDEX 9', '30576 Hollow Ridge Circle');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (14, 'France', 'Marseille', '13393 CEDEX 13', '4 Brentwood Plaza');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (15, 'France', 'Aurillac', '15004 CEDEX', '55905 Elmside Plaza');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (16, 'France', 'Vitry-sur-Seine', '94409 CEDEX', '1 Oak Valley Junction');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (17, 'France', 'Mont-de-Marsan', '40025 CEDEX', '87 Crowley Avenue');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (18, 'France', 'Tourcoing', '59208 CEDEX', '184 Fallview Hill');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (19, 'France', 'Chantilly', '60637 CEDEX', '70909 Schurz Lane');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (20, 'France', 'Gardanne', '13548 CEDEX', '6987 Derek Hill');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (21, 'France', 'Saint-Louis', '68309 CEDEX', '4050 Mayer Parkway');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (22, 'France', 'Paris 13', '75623 CEDEX 13', '3890 Onsgard Plaza');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (23, 'France', 'Aix-en-Provence', '13617 CEDEX 1', '2960 Luster Road');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (24, 'France', 'Bourges', '18013 CEDEX', '0 Aberg Plaza');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (25, 'France', 'Castelsarrasin', '82104 CEDEX', '58002 Garrison Terrace');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (26, 'France', 'Laval', '53085 CEDEX 9', '9 Coleman Road');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (27, 'France', 'Créteil', '94952 CEDEX 9', '3 Mcbride Trail');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (28, 'France', 'Saint-Ouen', '93487 CEDEX', '1 Kim Terrace');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (29, 'France', 'Besançon', '25024 CEDEX', '5 Coleman Street');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (30, 'France', 'Évry', '91914 CEDEX 9', '45060 Bonner Pass');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (31, 'Germany', 'Lübeck', '23568', '09 Sunfield Park');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (32, 'France', 'Créteil', '94049 CEDEX', '17 Myrtle Way');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (33, 'France', 'Ploemeur', '56274 CEDEX', '1167 Sunnyside Terrace');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (34, 'France', 'Paris 14', '75699 CEDEX 14', '61848 Saint Paul Point');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (35, 'France', 'Tours', '37044 CEDEX 9', '61 Eagle Crest Trail');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (36, 'France', 'Périgny', '17184 CEDEX', '3401 Eggendart Point');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (37, 'France', 'Aix-en-Provence', '13617 CEDEX 1', '167 Tony Pass');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (38, 'France', 'Alençon', '61042 CEDEX', '938 Oriole Circle');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (39, 'France', 'Roissy Charles-de-Gaulle', '95943 CEDEX 2', '80188 Holmberg Court');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (40, 'France', 'Toulouse', '31931 CEDEX 9', '400 Lunder Way');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (41, 'France', 'Perpignan', '66945 CEDEX', '0958 Kingsford Pass');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (42, 'France', 'Vincennes', '94685 CEDEX', '7 Briar Crest Park');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (43, 'Germany', 'Remscheid', '42897', '855 Pankratz Pass');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (44, 'France', 'Corbeil-Essonnes', '91815 CEDEX', '59190 Prairieview Lane');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (45, 'France', 'Paris 12', '75582 CEDEX 12', '220 Crescent Oaks Road');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (46, 'France', 'Noisy-le-Grand', '93462 CEDEX', '1 Warbler Hill');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (47, 'France', 'Castelnaudary', '11493 CEDEX', '53275 Ohio Drive');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (48, 'France', 'Blois', '41904 CEDEX 9', '4 Vernon Drive');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (49, 'France', 'Bastia', '20292 CEDEX', '9 Lukken Court');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (50, 'France', 'Quetigny', '21806 CEDEX', '9 Rusk Junction');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (51, 'France', 'Nice', '06173 CEDEX 2', '08187 Orin Junction');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (52, 'France', 'Paris 10', '75485 CEDEX 10', '4330 Luster Terrace');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (53, 'France', 'Alençon', '61042 CEDEX', '13 Londonderry Hill');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (54, 'France', 'Chambéry', '73091 CEDEX', '9815 Talmadge Pass');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (55, 'France', 'Saint-Brieuc', '22025 CEDEX 1', '0 Pierstorff Street');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (56, 'France', 'Avignon', '84033 CEDEX 3', '63 Harper Avenue');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (57, 'Germany', 'Berlin', '13599', '2 Continental Avenue');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (58, 'France', 'Cluses', '74311 CEDEX', '90 Paget Street');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (59, 'France', 'Besançon', '25086 CEDEX 9', '70 Becker Plaza');
insert into adresse (id, adr_pays, adr_ville, adr_postal, adr_adresse) values (60, 'Belgium', 'Mons', '7032', '5522 Hanson Drive');
